// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqqajzfkqushviwuayng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcWFqemZrcXVzaHZpd3VheW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM3MDgsImV4cCI6MjA2NTQ2OTcwOH0.RTNn8ehrm8R1PliR37bwB6I2WKVyqs1NnZIGMGV6WN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);